// generated by Glue Standard 5.0.1 (wsdl2java) on Fri Aug 27 12:11:21 BST 2004
package com.atlassian.confluence.remote;

public class RemotePage extends RemotePageSummary implements java.io.Serializable
  {
  public java.util.Date created;
  public java.util.Date modified;
  public String creator;
  public String modifier;
  public String content;
  public int version;
  public boolean homePage;
  }
