// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public class RemoteAttachment implements java.io.Serializable
  {
  public long id;
  public long pageId;
  public long fileSize;
  public String title;
  public String fileName;
  public String contentType;
  public String creator;
  public String url;
  public java.util.Date created;
  }
