// generated by Glue Standard 5.0.1 (wsdl2java) on Fri Aug 27 12:11:21 BST 2004
package com.atlassian.confluence.remote;

public class RemoteServerInfo implements java.io.Serializable
  {
  public int majorVersion;
  public int minorVersion;
  public int patchLevel;
  public boolean developmentBuild;
  public String buildId;
  public String baseUrl;
  }
