// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public class RemotePage extends RemotePageSummary implements java.io.Serializable
  {
  public java.util.Date created;
  public java.util.Date modified;
  public String creator;
  public String modifier;
  public String content;
  public int version;
  public boolean homePage;
  }
