// generated by Glue Standard 5.0.1 (wsdl2java) on Fri Aug 27 12:11:21 BST 2004
package com.atlassian.confluence.remote;

public class RemoteSpace extends RemoteSpaceSummary implements java.io.Serializable
  {
  public String description;
  public long homePage;
  }
