// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public class RemotePageHistory implements java.io.Serializable
  {
  public long id;
  public int version;
  public String modifier;
  public java.util.Date modified;
  }
