// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public class RemoteSearchResult implements java.io.Serializable
  {
  public String type;
  public long id;
  public String title;
  public String url;
  public String excerpt;
  }
