// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

import electric.registry.Registry;
import electric.registry.RegistryException;

public class ConfluenceSoapHelper
  {
  public static IConfluenceSoapService bind() throws RegistryException
    {
    return bind( "http://confluence.atlassian.com:8080/rpc/soap/confluenceservice-v1.wsdl" );
    }

  public static IConfluenceSoapService bind( String url ) throws RegistryException
    {
    return (IConfluenceSoapService) Registry.bind( url, IConfluenceSoapService.class );
    }
  }
