// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public interface IConfluenceSoapService
  {
  String[] getPermissions( String arg0, String arg1 );
  RemoteSearchResult[] search( String arg0, String arg1, int arg2 );
  String login( String arg0, String arg1 );
  boolean logout( String arg0 );
  RemoteUser getUser( String arg0, String arg1 );
  RemotePage getPage( String arg0, long arg1 );
  RemoteAttachment[] getAttachments( String arg0, long arg1 );
  RemoteSpace getSpace( String arg0, String arg1 );
  RemoteComment[] getComments( String arg0, long arg1 );
  boolean addGroup( String arg0, String arg1 );
  void addUser( String arg0, RemoteUser arg1, String arg2 );
  RemoteSpaceSummary[] getSpaces( String arg0 );
  RemotePageSummary[] getPages( String arg0, String arg1 );
  RemotePageHistory[] getPageHistory( String arg0, long arg1 );
  String renderContent( String arg0, String arg1, long arg2, String arg3 );
  Boolean deletePage( String arg0, long arg1 );
  RemotePage storePage( String arg0, RemotePage arg1 );
  String[] getUserGroups( String arg0, String arg1 );
  void addUserToGroup( String arg0, String arg1, String arg2 );
  RemoteSpace addSpace( String arg0, RemoteSpace arg1 );
  }
