// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public class RemoteSpace extends RemoteSpaceSummary implements java.io.Serializable
  {
  public String description;
  public long homePage;
  }
