// generated by Glue Professional 5.0 Beta2 (wsdl2java) on Sat Feb 28 00:36:10 GMT 2004
package com.atlassian.confluence.remote;

public class RemoteSpaceSummary implements java.io.Serializable
  {
  public String key;
  public String name;
  public String url;
  }
