// generated by Glue Standard 5.0.1 (wsdl2java) on Fri Aug 27 12:11:21 BST 2004
package com.atlassian.confluence.remote;

import electric.registry.Registry;
import electric.registry.RegistryException;

public class ConfluenceSoapHelper
  {
  public static IConfluenceSoapService bind() throws RegistryException
    {
    return bind( "file:/e:/temp/confluenceservice-v1.wsdl" );
    }

  public static IConfluenceSoapService bind( String url ) throws RegistryException
    {
    return (IConfluenceSoapService) Registry.bind( url, IConfluenceSoapService.class );
    }
  }
