// generated by Glue Standard 5.0.1 (wsdl2java) on Fri Aug 27 12:11:21 BST 2004
package com.atlassian.confluence.remote;

public class RemoteAttachment implements java.io.Serializable
  {
  public long id;
  public long pageId;
  public long fileSize;
  public String title;
  public String fileName;
  public String contentType;
  public String creator;
  public String url;
  public java.util.Date created;
  }
