// generated by Glue Standard 5.0.1 (wsdl2java) on Fri Aug 27 12:11:21 BST 2004
package com.atlassian.confluence.remote;

public class RemoteSearchResult implements java.io.Serializable
  {
  public String type;
  public long id;
  public String title;
  public String url;
  public String excerpt;
  }
